import React,{useEffect,useMemo,useState} from 'react';
import {Container,Row,Col,Card,Button,Alert,Form,Badge} from 'react-bootstrap';
import {useSearchParams} from 'react-router-dom';
import NavigationBar from '../components/NavigationBar';
import LoadingSpinner from '../components/LoadingSpinner';
import votingService from '../services/votingService';

function Countdown({end}){const [now,setNow]=useState(Date.now());useEffect(()=>{const i=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(i)},[]);const d=Math.max(0,new Date(end)-now);const s=Math.floor(d/1000),h=Math.floor(s/3600),m=Math.floor(s%3600/60),sec=s%60;return <div className="countdown"><span>{String(h).padStart(2,'0')}h</span><span>{String(m).padStart(2,'0')}m</span><span>{String(sec).padStart(2,'0')}s</span></div>}

export default function Vote(){
 const [params,setParams]=useSearchParams();const [elections,setElections]=useState([]);const [electionId,setElectionId]=useState(params.get('election')||'');const [positions,setPositions]=useState([]),[status,setStatus]=useState(null),[selected,setSelected]=useState({}),[error,setError]=useState(''),[success,setSuccess]=useState(''),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false);
 const election=useMemo(()=>elections.find(e=>String(e.id)===String(electionId)),[elections,electionId]);
 const load=async()=>{try{const es=await votingService.getElections();setElections(es);let id=electionId||es.find(e=>e.status==='voting')?.id||es[0]?.id;if(id&&!electionId){setElectionId(String(id));setParams({election:String(id)})}if(id){const [ps,st]=await Promise.all([votingService.getPositions(id),votingService.getVotingStatus(id)]);setPositions(ps);setStatus(st.elections?.[0])}}catch(err){setError('Could not load election data.')}finally{setLoading(false)}};useEffect(()=>{load();const i=setInterval(load,3000);return()=>clearInterval(i)},[electionId]);
 const submit=async(p)=>{const c=selected[p.id];if(!c)return;setSubmitting(true);setError('');try{await votingService.castVote({candidate:c,position:p.id});setSuccess(`Vote recorded for ${p.name}.`);const st=await votingService.getVotingStatus(electionId);setStatus(st.elections?.[0]);setSelected({...selected,[p.id]:null})}catch(err){setError(err.response?.data?.non_field_errors?.[0]||'Vote could not be submitted.')}finally{setSubmitting(false)}};
 if(loading)return <LoadingSpinner message="Loading voting booth..."/>;
 return <><NavigationBar/><main className="content-wrapper"><Container>
 <div className="d-flex flex-wrap justify-content-between align-items-center mb-4"><div><h2>Voting Booth</h2><p className="text-muted mb-0">Select one candidate for each position.</p></div><Form.Select value={electionId} onChange={e=>{setElectionId(e.target.value);setParams({election:e.target.value})}} style={{maxWidth:320}}>{elections.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</Form.Select></div>
 {election&&<Card className="timer-card border-0 mb-4"><Card.Body><div className="d-flex flex-wrap justify-content-between align-items-center"><div><strong>{election.name}</strong><div className="small opacity-75">{election.status==='voting'?'Voting is open':'Voting is '+election.status}</div></div>{election.status==='voting'?<Countdown end={election.end_time}/>:<Badge bg="light" text="dark">{election.status}</Badge>}</div></Card.Body></Card>}
 {error&&<Alert variant="danger" onClose={()=>setError('')} dismissible>{error}</Alert>}{success&&<Alert variant="success">{success}</Alert>}
 {election?.status!=='voting'&&<Alert variant="warning">{election?.status==='closed'?'Voting has ended.':'Voting has not started yet.'}</Alert>}
 {positions.map(p=>{const has=status?.voting_status?.find(x=>x.position_id===p.id)?.has_voted;return <Card className="mb-4 border-0 shadow-sm" key={p.id}><Card.Body><div className="d-flex justify-content-between"><div><h4>{p.name}</h4><p className="text-muted">{p.description}</p></div>{has&&<Badge bg="success" className="h-100">Voted</Badge>}</div>{has?<Alert variant="success" className="mb-0">Your ballot for this position has been recorded.</Alert>:<><Row className="g-3">{p.candidates.filter(c=>c.is_active).map(c=><Col md={6} lg={4} key={c.id}><Card onClick={()=>setSelected({...selected,[p.id]:c.id})} className={`candidate-card h-100 ${selected[p.id]===c.id?'selected':''}`}><Card.Body><Form.Check type="radio" checked={selected[p.id]===c.id} onChange={()=>setSelected({...selected,[p.id]:c.id})} label={<strong>{c.name}</strong>}/>{c.bio&&<p className="small text-muted mt-2 mb-0">{c.bio}</p>}</Card.Body></Card></Col>)}</Row><div className="text-end mt-3"><Button className="btn-green" disabled={election?.status!=='voting'||!selected[p.id]||submitting} onClick={()=>submit(p)}>Submit Vote</Button></div></>}</Card.Body></Card>})}
 </Container></main></>
}
